### PR TITLE
Fix TS2306 “not a module” errors in type definitions

### LINKED ISSUE #24: [1.0.2 regression] TypeScript error TS2306: File '…/source-map.d.ts' is not a module
```console
$ npm i source-map@npm:source-map-js@1.2.0 typescript

added 2 packages in 2s

$ echo 'import * as SourceMap from "source-map"' > test.ts

$ npx tsc test.ts 
test.ts:1:28 - error TS2306: File '/tmp/node_modules/source-map/source-map.d.ts' is not a module.

1 import * as SourceMap from "source-map"
                             ~~~~~~~~~~~~


Found 1 error in test.ts:1
```

This worked in 1.0.1 and regressed in 1.0.2. I explained the reason at https://github.com/7rulnik/source-map-js/pull/13#pullrequestreview-1325506171: the `declare module` syntax is only for stubbing third-party modules. To declare modules in the current package, you should just write a separate `.d.ts` file for each `.js` file.

- 7rulnik/source-map-js#16

### PR DESCRIPTION
**Pull request by andersk**
Fixes TypeScript errors like this when substituting source-map-js for source-map using pnpm overrides.

    node_modules/.pnpm/css-minimizer-webpack-plugin@4.2.2_dpcjkp5o5ztxuvt4quwwvenemi/node_modules/css-minimizer-webpack-plugin/types/index.d.ts:141:28 - error TS2306: File '/srv/zulip/node_modules/.pnpm/source-map-js@1.0.2/node_modules/source-map-js/source-map.d.ts' is not a module.

    141 type RawSourceMap = import("source-map").RawSourceMap;
                                   ~~~~~~~~~~~~

- Fixes #24.

### CODE REVIEW

**Comment by 7rulnik** [comment]
@andersk Hi! It's not clear to me: why it wasn't a problem before 1.0.2?

**Comment by andersk** [comment]
@7rulnik This was broken by the incorrect usage of `declare module` that was added in #13, which was merged in 1.0.2.

See the reproduction recipe in #24.

**Comment by 7rulnik** [comment]
Ahhh, my bad! For some reason, I read 1.0.2 as 1.2.0 and was really confused about it. Sorry!
I will take a look into it a bit later!

**Comment by 7rulnik** [comment]
Thanks for PR and sorry for waiting!
Published as https://www.npmjs.com/package/source-map-js/v/1.2.1
